# Generated by Django 2.2.4 on 2019-08-26 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter',
            old_name='count',
            new_name='visits',
        ),
    ]
