# Generated by Django 2.2.4 on 2019-08-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_auto_20190826_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
